baseURL = "https://www.lifepoints.net/"
languageCode = "en-us"
title = "LifePoints"
theme = "ananke"
enableRobotsTXT = true
googleAnalytics= "UA-1382626-4"
disqusShortname= "lifepoints-net"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Health"
  weight = 10
  identifier = "Health"
  url = "/tags/health/"

[[menu.main]]
  name = "Food"
  weight = 11
  identifier = "Food"
  url = "/tags/food/"
  
[[menu.main]]
  name = "Parenthood"
  weight = 12
  identifier = "Parenthood"
  url = "/tags/parenthood/"

[[menu.main]]
  name = "Travel"
  weight = 13
  identifier = "Travel"
  url = "/tags/travel/"
  
  
[[menu.main]]
  name = "Inspiration"
  weight = 14
  identifier = "Inspiration"
  url = "/tags/inspiration/"

[[menu.main]]
  name = "Subscribe"
  weight = 15
  identifier = "Subscribe"
  url = "/subscribe"

# Add your own params here
[params]
  author = "Nicole D."
  favicon= "images/avatar.jpg"
  description= "Pointers for your everyday life"
  seotitle = "Pointers for your everyday life"
  subtitle = "A new mama sharing about health, food, lifestyle, travel & inspiration"
  paginate = 10
  instagram = "https://instagram.com/life_points"
  twitter =  "https://twitter.com/_LifePoints"
  background_color_class = "bg-mid-gray"
  featured_image="images/bruno-cervera-368194.jpg"
